import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { incidentAPI } from '../lib/api'

export default function IncidentImpactPanel({ incidentId }: { incidentId: string }) {
  const [preview, setPreview] = useState<string | null>(null)
  const impact = useQuery({ queryKey: ['incident-impact', incidentId], queryFn: () => incidentAPI.impact(incidentId).then(response => response.data) })
  if (impact.isLoading) return <section className="bg-white p-6 rounded-lg shadow"><p className="text-slate-500">Loading potentially affected customers...</p></section>
  if (impact.isError || !impact.data) return <section className="bg-white p-6 rounded-lg shadow"><p className="text-slate-500">Customer impact is unavailable for this incident.</p></section>
  return <section className="bg-white p-6 rounded-lg shadow"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-wider text-slate-500">Incident impact</p><h2 className="text-lg font-semibold">Potentially Affected Customers</h2><p className="text-sm text-slate-500 mt-1">{impact.data.affected_customer_count} customers · {impact.data.affected_orders} orders · {(impact.data.confidence * 100).toFixed(0)}% confidence</p></div><Link to={`/intelligence-graph?entity=incident&id=${incidentId}`} className="text-sm text-blue-600 hover:underline">View in Graph</Link></div><div className="overflow-x-auto mt-4"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500 border-b"><th className="py-2">Customer</th><th>Order</th><th>Reason</th><th>Risk</th><th>Action</th></tr></thead><tbody>{impact.data.affected_customers.map(customer => <tr key={customer.customer_id} className="border-b last:border-0"><td className="py-3"><Link className="text-blue-600 hover:underline" to={`/customers/${customer.customer_id}`}>{customer.customer}</Link></td><td>{customer.order_id || 'Not linked'}</td><td>{customer.reason}</td><td><span className={customer.risk === 'HIGH' ? 'text-red-600 font-semibold' : 'text-amber-600 font-semibold'}>{customer.risk}</span></td><td><button onClick={() => setPreview(customer.customer_id)} className="text-blue-600 hover:underline">Preview Outreach</button></td></tr>)}</tbody></table></div>{preview && <div className="mt-5 border border-blue-200 bg-blue-50 rounded-lg p-4"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase tracking-wider text-blue-700">Recommended outreach</p><p className="font-semibold mt-1">Potential logistics delay</p></div><button onClick={() => setPreview(null)} className="text-sm text-slate-500">Dismiss</button></div><p className="text-sm text-slate-700 mt-3">We wanted to let you know that your order may experience a delivery delay while this potential operational issue is investigated.</p><div className="flex gap-2 mt-4"><button className="px-3 py-2 rounded bg-blue-600 text-white text-sm">Approve</button><button className="px-3 py-2 rounded border border-slate-300 text-sm">Edit</button></div></div>}</section>
}
